config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cvs.contentguide:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.cvs.contentguide
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cvs.contentguide git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-amaranth-javanese.sh
        container: qc.acc_flaky-firebrick-cougar
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cvs.contentguide find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-apricot-swan.sh
        container: qc.doc_freaky-ruby-crane
      bitbucket.org/cessda/cessda.cvs.contentguide git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-tangerine-shrimp.sh
        container: qc.doc_droopy-red-fowl
      bitbucket.org/cessda/cessda.cvs.contentguide markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-mustard-tiger.sh
        container: qc.doc_gummy-amber-kakapo
      bitbucket.org/cessda/cessda.cvs.contentguide restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-beige-snake.sh
        container: qc.doc_pretty-denim-chin
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cvs.contentguide licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-xanthic-cichlid.sh
        container: qc.lic_skinny-ivory-fowl
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cvs.contentguide jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-myrtle-mayfly.sh
        container: qc.sty_hilly-cinnamon-goose
      bitbucket.org/cessda/cessda.cvs.contentguide rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-cobalt-capuchin.sh
        container: qc.sty_stuffy-zucchini-llama
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cvs.contentguide get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-turquoise-hyrax.sh
        container: qc.ver_sleazy-dandelion-foxhound
timeout: 5400
